services:
  # 백엔드 서비스만 배포 (프론트엔드는 GitHub Pages 사용)
  - type: web
    name: ahp-forpaper
    env: node
    buildCommand: cd backend && npm ci && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/health