name: Deploy Backend to Render

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-backend:
    name: Deploy Backend to Render
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install and build backend
      run: |
        cd backend
        npm ci
        npm run build
        
    - name: Notify deployment start
      run: |
        echo "🚀 Backend deployment started for commit ${{ github.sha }}"
        echo "Backend will be deployed to Render.com via webhook"
        
    - name: Trigger Render deployment
      run: |
        echo "Render.com will automatically deploy from this GitHub push"
        echo "Check deployment status at: https://dashboard.render.com"
        echo "API URL: https://ahp-forpaper.onrender.com"